import { ServerSideProvider } from '../context/ServerSideContext'
import '../globals.css'


export const metadata = {
  title: 'AutoSync Admin Dashboard',
  description: 'Generated by gharis',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
       <ServerSideProvider>
        {children}
       </ServerSideProvider>
      </body>
    </html>
  )
}
