import NavComponent from '@/components/NavComponent'
//import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'
import { CartProvider } from '@/context/CartContext'
//import {Session, getServerSession} from 'next-auth';
//import { headers } from 'next/headers';
//import { authOption } from './api/auth/[...nextauth]/route';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'AutoSync',
//   description: 'Generated by create next app',
// }


export default  function ClientLayout({children}:{children:React.ReactNode}) {
  
  return (
    // <html lang="en">
    //   <head/>
      // <body className={inter.className} suppressHydrationWarning={true}>
        <Provider>
          <CartProvider>
            <NavComponent/>
            {children}  
          </CartProvider>
        </Provider>    
      // </body>
    // </html>
  )
}
