import React from 'react'
import './globals.css'


export const metadata = {
  title: 'AutoSync Admin Dashboard',
  description: 'Generated by gharis',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
